CREATE TABLE TB_ESTILO (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE TB_CERVEJA (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    SKU VARCHAR(50) NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    TEOR_ALCOOLICO DECIMAL(10, 2) NOT NULL,
    COMISSAO DECIMAL(10, 2) NOT NULL,
    SABOR VARCHAR(50) NOT NULL,
    ORIGEM VARCHAR(50) NOT NULL,
    ID_TB_ESTILO BIGINT(20) NOT NULL,
    FOREIGN KEY (ID_TB_ESTILO) REFERENCES TB_ESTILO(ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

INSERT INTO TB_ESTILO VALUES (0, 'Amber Lager');
INSERT INTO TB_ESTILO VALUES (0, 'Dark Lager');
INSERT INTO TB_ESTILO VALUES (0, 'Pale Lager');
INSERT INTO TB_ESTILO VALUES (0, 'Pilsner');